# Generated by Django 6.0.3 on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_session_base_price_and_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="status",
            field=models.CharField(
                choices=[
                    ("em_cartaz", "Em cartaz"),
                    ("pre_venda", "Pre-venda"),
                    ("em_breve", "Em breve"),
                ],
                default="em_cartaz",
                max_length=20,
            ),
        ),
    ]
