# Generated by Django 6.0.3 on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_movie_status_em_breve"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="room",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="room",
            name="experience_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("standard", "Traditional"),
                    ("vip", "VIP"),
                    ("premium", "Premium"),
                    ("imax", "IMAX"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="audio_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("original", "Original"),
                    ("legendado", "Subtitled"),
                    ("dublado", "Dubbed"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="projection_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2d", "2D"),
                    ("3d", "3D"),
                    ("imax", "IMAX"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="session_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("regular", "Regular"),
                    ("preview", "Preview"),
                    ("special_event", "Special event"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
