# Generated by Django 6.0.3 on 2026-07-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0021_add_classification_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
