# Generated by Django 6.0.3 on 2026-07-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0022_movie_trailer_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="ticket_image_url",
            field=models.URLField(
                blank=True,
                help_text="Imagem horizontal (paisagem), proporção ideal 16:9 (ex.: 1280×720).",
                max_length=500,
                null=True,
                verbose_name="Imagem de fundo do ingresso",
            ),
        ),
    ]
