# Generated by Django 6.0.3 on 2026-07-07 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0013_alter_ticket_ticket_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="session_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="session_seat",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket",
                to="reservations.sessionseat",
            ),
        ),
    ]
