# Generated by Django 6.0.3 on 2026-07-05 05:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reason', models.CharField(choices=[('refund', 'Refund'), ('purchase', 'Purchase'), ('adjustment', 'Adjustment')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Optional reference to the originating record (e.g. ticket code).', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='wallet_tx_user_idx')],
            },
        ),
    ]
